### ISSUE TITLE
verbose mode

### ISSUE THREAD

**Issue by patmtp35** [E-t0m/zeroinput#1]
hi,

trying to use you re script in verbose mode but nothing happened.

script start and have to ctrl-c to break it.

as i read in the script i put vzlogger.conf in etc before create the fifo file.

my esmart3 was Version 4.2 could get data via solarmate pc or solarmate android

**Comment by E-t0m** [comment]
hi! did you see the [building instructions](https://github.com/E-t0m/zeroinput/blob/main/about_en.md)?

there is a [esmart_test.py](https://github.com/E-t0m/esmart_mppt/blob/master/esmart_test.py) delivered with the lib, try to connect with this first.

you need to setup the volkszaehler before you can run zero_input.py

**Comment by patmtp35** [comment]
hi yes i read instruction as i m french could have done mistake :)

ok i understand now that's because i don't have volszaehler :(

i ran the emsart_test.py only working if with the y cable i made , i ran solarmate when solarmate ask the esmart , esmart_test.py recive datas . 
as if esmart_test.py couldn't ask it self :(
<img width="222" alt="image" src="https://user-images.githubusercontent.com/6410695/224568935-b1a2b07b-0fb2-40b3-8699-08a2f90fd9fb.png">

**Comment by E-t0m** [comment]
This sounds like a wiring problem.
But sorry this is not related to zeroinput.
